# Creat by Abraão Silva
# Date 12 Nov 2018 
version: '3'
services:
  jfrog-artifactory:
    container_name: jfrog-artifactory
    image: docker.bintray.io/jfrog/artifactory-oss
    volumes:
      - "$PWD/artifactory-data/data:/var/opt/jfrog/artifactory/data"
      - "$PWD/artifactory-data/logs:/var/opt/jfrog/artifactory/logs"
      - "$PWD/artifactory-data/backup:/var/opt/jfrog/artifactory/backup"
      - "$PWD/artifactory-data/etc:/var/opt/jfrog/artifactory/etc"
    restart: always
# environment:
    ports:
     - '4000:8081'
#     - '5005:5005'
#     - '5006:5006'
#     - '5007:5007'
