# Creat by Abraão Silva
# Date 12 Nov 2018 
version: '3'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.1
    restart: always 
    user: root
    volumes:
    - "$PWD/var/run/docker.sock:/var/run/docker.sock"
    - "$PWD//var/lib/docker/containers:/var/lib/docker/containers:ro"
    - "$PWD/etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
