http.host: 0.0.0.0

# custer.routing.allocation.disk.threshold_enabled: true
# cluster.routing.allocation.disk.watermark.low: 95%
# cluster.routing.allocation.disk.watermark.high: 50gb
# cluster.info.update.interval": 1m

# Uncomment the following lines for a production cluster deployment
# transport.host: 0.0.0.0
# discovery.zen.minimum_master_nodes: 1
#
#
